spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
