package com.example.worker_service.service;

import com.example.worker_service.exception.ConversionFailedException;
import com.example.worker_service.model.dto.FileJob;
import com.example.worker_service.model.dto.FileUpdateRequest;
import com.example.worker_service.model.dto.FileVariantDto;
import com.example.worker_service.model.enums.FileStatus;
import com.example.worker_service.util.UpdateInternalUtils;
import com.example.worker_service.util.VariantUtils;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.connection.Message;
import org.springframework.data.redis.connection.MessageListener;
import org.springframework.stereotype.Service;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class DocPreviewWorker implements MessageListener {

    private final MinioStorageService minioStorageService;
    private final UpdateInternalUtils updateInternalUtils;
    private final ObjectMapper objectMapper;
    private final VariantUtils variantUtils;

    private static final String TMP_DIR = "/tmp/preview";

    @Override
    public void onMessage(Message message, byte[] pattern) {
        try {
            FileJob job = objectMapper.readValue(message.getBody(), FileJob.class);
            log.info("Received preview job for fileId: {} ({})", job.getFileId(), job.getObjectKey());
            processJob(job);
        } catch (IOException e) {
            log.error("Failed to process message: {}", e.getMessage(), e);
        }
    }

    private void processJob(FileJob job) {
        String status = FileStatus.COMPLETED.name();
        List<FileVariantDto> variants = new ArrayList<>();

        try {
            Files.createDirectories(Path.of(TMP_DIR));
            Path inputFile = Path.of(TMP_DIR, job.getFileId().toString());
            Path previewFile = Path.of(TMP_DIR, job.getFileId() + "_preview.png");

            try (InputStream in = minioStorageService.getObject(job.getObjectKey())) {
                Files.copy(in, inputFile);
            }

            BufferedImage preview = generatePreview(job.getMimeType(), inputFile.toFile(), previewFile.toFile());
            if (preview != null) {
                variants = variantUtils.generateImageVariants(job.getObjectKey(), preview);
            }

            Files.deleteIfExists(inputFile);
            Files.deleteIfExists(previewFile);

        } catch (Exception e) {
            status = FileStatus.FAILED.name();
            log.error("Error generating preview for fileId {}: {}", job.getFileId(), e.getMessage(), e);
        } finally {
            FileUpdateRequest update = FileUpdateRequest.builder()
                    .fileId(job.getFileId())
                    .status(status)
                    .variants(variants)
                    .build();
            updateInternalUtils.updateInternal(job, update);
        }
    }

    private BufferedImage generatePreview(String mimeType, File inputFile, File previewFile) throws Exception {
        if (mimeType == null)
            return null;

        // Handle LibreOffice-compatible docs
        convertWithLibreOffice(inputFile, previewFile);
        if (previewFile.exists()) {
            return ImageIO.read(previewFile);
        }
        return null;
    }

    private void convertWithLibreOffice(File inputFile, File outputFile) throws IOException, InterruptedException {
        File outputDir = outputFile.getParentFile();
        String command = String.format(
                "libreoffice --headless --convert-to png --outdir %s %s",
                outputDir.getAbsolutePath(),
                inputFile.getAbsolutePath()
        );

        log.info("Running LibreOffice command: {}", command);
        Process process = Runtime.getRuntime().exec(command);
        int exitCode = process.waitFor();

        if (exitCode == 0) {
            // LibreOffice creates file with same base name but .png extension
            File[] pngs = outputDir.listFiles((dir, name) -> name.endsWith(".png"));
            if (pngs != null && pngs.length > 0) {
                Files.move(pngs[0].toPath(), outputFile.toPath());
                log.info("LibreOffice conversion successful: {}", outputFile.getName());
            } else {
                log.warn("No PNG generated by LibreOffice for {}", inputFile.getName());
            }
        } else {
            try (BufferedReader br = new BufferedReader(new InputStreamReader(process.getErrorStream()))) {
                br.lines().forEach(log::error);
            }
            throw new ConversionFailedException("LibreOffice conversion failed with exit code " + exitCode);
        }
    }
}
